definitions:
  steps:
    - step: &business-build
        name: Build Business
        image: openjdk:11-jdk-slim
        caches:
          - gradle
        script:
          - cd business
          - ./gradlew clean build

    - step: &ui-build
        name: Build UI
        image: node:14-slim
        script:
          - cd ui
          - npm install

pipelines:
  default:
    - parallel:
      - step: *business-build
      - step: *ui-build


